name: Deploy Azure Base Environment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_RESOURCE_GROUP: ${{ values.resourceGroupName }}
      AZURE_ADMIN_SSH_PUBLIC_KEY: ${{ vars.AZURE_ADMIN_SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ env.AZURE_CLIENT_ID }}

      - name: Deploy base bicep
        run: |
          az deployment group create \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --template-file "infra/environments/${{ values.environmentName }}/base/main.bicep" \
            --parameters adminSshPublicKey="$AZURE_ADMIN_SSH_PUBLIC_KEY"
