apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-${{ values.environmentName }}-vm-${{ values.workloadName }}
  description: Azure VM add-on for existing environment ${{ values.environmentName }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
spec:
  type: infrastructure
  owner: ${{ values.owner }}
  lifecycle: experimental
